type ImageMapType = {[key: string]: ReturnType<typeof require>};

export const imageMap: ImageMapType = {
  '../InterviewQuestions/images/react/state.jpg': require('../images/react/state.jpg'),
  '../InterviewQuestions/images/react/vdom1.png': require('../images/react/vdom1.png'),
  '../InterviewQuestions/images/react/vdom2.png': require('../images/react/vdom2.png'),
  '../InterviewQuestions/images/react/vdom3.png': require('../images/react/vdom3.png'),
  '../InterviewQuestions/images/systems_design/cap.png': require('../images/systems_design/cap.png'),
  '../InterviewQuestions/images/systems_design/load_balancing.png': require('../images/systems_design/load_balancing.png'),
  '../InterviewQuestions/images/systems_design/rate_limiter.png': require('../images/systems_design/rate_limiter.png'),
  '../InterviewQuestions/images/systems_design/rate_limiter2.png': require('../images/systems_design/rate_limiter2.png'),
  '../InterviewQuestions/images/systems_design/consistent_hashing.png': require('../images/systems_design/consistent_hashing.png'),
  '../InterviewQuestions/images/systems_design/consistent_hashing2.png': require('../images/systems_design/consistent_hashing2.png'),
  '../InterviewQuestions/images/systems_design/key_value_store.png': require('../images/systems_design/key_value_store.png'),
  '../InterviewQuestions/images/systems_design/key_value_store2.png': require('../images/systems_design/key_value_store2.png'),
  '../InterviewQuestions/images/systems_design/key_value_store3.png': require('../images/systems_design/key_value_store3.png'),
  '../InterviewQuestions/images/systems_design/key_value_store4.png': require('../images/systems_design/key_value_store4.png'),
  '../InterviewQuestions/images/systems_design/key_value_store5.png': require('../images/systems_design/key_value_store5.png'),
  '../InterviewQuestions/images/systems_design/key_value_store6.png': require('../images/systems_design/key_value_store6.png'),
  '../InterviewQuestions/images/systems_design/key_value_store7.png': require('../images/systems_design/key_value_store7.png'),
  '../InterviewQuestions/images/systems_design/key_value_store8.png': require('../images/systems_design/key_value_store8.png'),
  '../InterviewQuestions/images/systems_design/key_value_store9.png': require('../images/systems_design/key_value_store9.png'),
  '../InterviewQuestions/images/systems_design/key_value_store10.png': require('../images/systems_design/key_value_store10.png'),
  '../InterviewQuestions/images/systems_design/key_value_store11.png': require('../images/systems_design/key_value_store11.png'),
};
